apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mission-deployment
spec:
  selector:
    matchLabels:
      app: mission
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mission
    spec:
      containers:
        - name: mission
          image:  subhamsingh99/projecto:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster

